replicaCount: 10
domain: "elastic-training.erben.tech"
letsencryptEmail: "alex@it-erben.com"

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch
  tag: "9.3.0"
  heapSize: "768m"
  storage: "10Gi"

kibana:
  image: docker.elastic.co/kibana/kibana
  tag: "9.3.0"

elasticPassword: "changeme"
encryptionKey: ""
