# yamllint disable-file
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elastic-training.fullname" . }}
  labels:
    {{- include "elastic-training.labels" . | nindent 4 }}
type: Opaque
stringData:
  elastic-password: {{ .Values.elasticPassword | quote }}
  encryption-key: {{ include "elastic-training.encryptionKey" . | quote }}
